### ISSUE TITLE
提楼的不能用了吗

### ISSUE THREAD

**Issue by GHang9** [nodeloc/hostloc_auto#4]
提楼的不能用了吗

**Comment by nodeloc** [comment]
有什么问题么。应该可以用的。

**Comment by GHang9** [comment]
> 有什么问题么。应该可以用的。

已经登录成功，但是T楼的时候提示这个
![屏幕截图 2023-11-29 084203.png](https://pic.ziyuan.wang/2023/11/29/guest_d48a17686b6ae.png)

**Comment by GHang9** [comment]
2023-11-28 13:52:54,772 Snapped.py reply：line 115 ERROR T楼发送失败	<?xml version="1.0" encoding="utf-8"?>
<root><![CDATA[<h3 class="flb"><em>提示信息</em><span><a href="javascript:;" class="flbc" onclick="hideWindow('fastpost');" title="关闭">关闭</a></span></h3>
<div class="c altw">
<div class="alert_error">抱歉，您的请求来路不正确或表单验证串不符，无法提交<script type="text/javascript" reload="1">if(typeof errorhandle_fastpost=='function') {errorhandle_fastpost('抱歉，您的请求来路不正确或表单验证串不符，无法提交', {});}</script></div>
</div>
<p class="o pns">
<button type="button" class="pn pnc" id="closebtn" onclick="hideWindow('fastpost');"><strong>确定</strong></button>
<script type="text/javascript" reload="1">if($('closebtn')) {$('closebtn').focus();}</script>
</p>
]]></root>

**Comment by nodeloc** [comment]
有空我修复一下。

**Comment by zhiqing0205** [comment]
蹲

**Comment by nodeloc** [comment]
已经处理好了。
